<?php
require __DIR__.'/bootstrap.php';
function second_review_expect(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$root=dirname(__DIR__).'/plugin/xsofty-wordpress-mcp/includes';
$auth=file_get_contents($root.'/class-xsofty-mcp-auth.php');
$admin=file_get_contents($root.'/class-xsofty-mcp-admin.php');
$jobs=file_get_contents($root.'/class-xsofty-mcp-jobs.php');
$backups=file_get_contents($root.'/class-xsofty-mcp-backups.php');
$tools=file_get_contents($root.'/class-xsofty-mcp-tools.php');
$server=file_get_contents($root.'/class-xsofty-mcp-server.php');
second_review_expect(str_contains($auth,'update_settings(callable $callback)'),'Shared settings need an atomic mutation API.');
second_review_expect(str_contains($auth,'policy_records_for_storage'),'Usage telemetry must be stripped before token-policy persistence.');
second_review_expect(str_contains($auth,'increment_database_limit'),'Object-cache increment failures must use the database limiter.');
second_review_expect(str_contains($auth,'development_http_allowed'),'HTTP opt-in must also require a development/private context.');
second_review_expect(str_contains($tools,"current_user_can('edit_themes')"),'Theme mutation must honor the native edit_themes capability.');
second_review_expect(str_contains($backups,'with_creation_lock'),'All backup creation paths must share one centralized lock.');
second_review_expect(str_contains($backups,'for($attempt=0;$attempt<10;$attempt++)')&&str_contains($backups,'Unable to remove private backup staging; the archive was not published.'),'Backup staging cleanup must retry and fail closed before publication.');
second_review_expect(str_contains($jobs,'recover_stale_jobs')&&str_contains($jobs,"'lease_expires_at'"),'Interrupted running backup jobs need stale-state recovery.');
second_review_expect(str_contains($jobs,'Unable to queue a backup retry.'),'Failed busy-lock retry scheduling must terminally fail the job.');
second_review_expect(!str_contains($admin,"\$settings['backup_schedule']="),'Admin global save must not pre-write schedule settings.');
second_review_expect(str_contains($server,'validate_method_params'),'Every supported MCP method needs bounded parameter validation before notification handling.');
$badPing=Xsofty_MCP_Server::handle(new WP_REST_Request(['MCP-Protocol-Version'=>'2025-06-18'],['jsonrpc'=>'2.0','id'=>1,'method'=>'ping','params'=>['unexpected'=>true]]));
second_review_expect($badPing->get_status()===400,'Ping must reject unexpected parameters.');
$badRead=Xsofty_MCP_Server::handle(new WP_REST_Request(['MCP-Protocol-Version'=>'2025-06-18'],['jsonrpc'=>'2.0','id'=>2,'method'=>'resources/read','params'=>['uri'=>['not-a-string']]]));
second_review_expect($badRead->get_status()===400,'resources/read must reject non-string URIs without casting warnings.');
$badNotification=Xsofty_MCP_Server::handle(new WP_REST_Request(['MCP-Protocol-Version'=>'2025-06-18'],['jsonrpc'=>'2.0','method'=>'ping','params'=>['unexpected'=>true]]));
second_review_expect($badNotification->get_status()===202,'Invalid notification parameters must remain bodyless while being validated and not executed.');
$created=Xsofty_MCP_Auth::create_token('Second review QA',1,['site_read']);
$settings=Xsofty_MCP_Auth::settings();$settings['allow_http']=true;Xsofty_MCP_Auth::save($settings);
$GLOBALS['xwmcp_ssl']=false;$GLOBALS['xwmcp_environment']='production';$GLOBALS['xwmcp_home_url']='http://public.example.com';
$publicHttp=Xsofty_MCP_Auth::authorize(new WP_REST_Request(['Authorization'=>'Bearer '.$created['token']]));
second_review_expect(is_wp_error($publicHttp)&&$publicHttp->get_error_code()==='xsofty_mcp_https_required','Explicit HTTP opt-in must still fail on a public production host.');
$GLOBALS['xwmcp_environment']='local';$GLOBALS['xwmcp_home_url']='http://wordpress-dev.local';
$localHttp=Xsofty_MCP_Auth::authorize(new WP_REST_Request(['Authorization'=>'Bearer '.$created['token']]));
second_review_expect($localHttp===true,'Explicit HTTP opt-in must work for a private .local host.');
Xsofty_MCP_Auth::update_token($created['id'],['name'=>'Telemetry isolation QA']);
$stored=(array)get_option(Xsofty_MCP_Auth::OPTION_KEY,[]);second_review_expect(!array_key_exists('last_used_at',(array)($stored['tokens'][$created['id']]??[])),'Usage telemetry must never be copied into token policy.');
Xsofty_MCP_Auth::end_request();$GLOBALS['xwmcp_ssl']=true;$GLOBALS['xwmcp_environment']='production';$GLOBALS['xwmcp_home_url']='https://example.test';$GLOBALS['xwmcp_ext_object_cache']=true;$GLOBALS['xwmcp_cache_incr_fails']=true;
$limited=null;for($i=0;$i<31;$i++)$limited=Xsofty_MCP_Auth::authorize(new WP_REST_Request(['Authorization'=>'Bearer invalid']));
second_review_expect(is_wp_error($limited)&&$limited->get_error_code()==='xsofty_mcp_rate_limited','Failed object-cache increments must fall back to the database limiter.');
$stale=Xsofty_MCP_Auth::settings();second_review_expect(Xsofty_MCP_Auth::revoke_token($created['id']),'QA token revocation failed.');$stale['rate_limit']=333;Xsofty_MCP_Auth::save($stale);$afterStale=(array)get_option(Xsofty_MCP_Auth::OPTION_KEY,[]);second_review_expect(!isset($afterStale['tokens'][$created['id']]),'A stale settings writer resurrected a revoked token.');
print("SECOND_REVIEW_BLOCKERS_PASS\n");
