<?php
if (!defined('ABSPATH')) exit;

final class Xsofty_MCP_Admin {
    public static function preset_definitions(): array {
        $read=['site_info','list_content','get_content','list_content_revisions','list_taxonomies','list_terms','get_registered_meta','list_menus','get_seo_status','get_seo_metadata','get_sitemap_status','get_site_health'];
        $content=array_merge($read,['create_content','update_content','restore_content_revision','create_term','update_term','assign_terms','update_registered_meta','update_menu_item','update_media_metadata','set_featured_image','update_seo_metadata','delete_content','list_media','upload_media_from_url']);
        $seo=['site_info','list_content','get_content','create_content','update_content','list_content_revisions','list_taxonomies','list_terms','get_registered_meta','update_registered_meta','list_media','update_media_metadata','set_featured_image','upload_media_from_url','get_seo_status','get_seo_metadata','update_seo_metadata','list_redirects','upsert_redirect','delete_redirect','get_sitemap_status'];
        $maintenance=['site_info','get_site_health','get_sitemap_status','list_plugins','list_plugin_updates','update_plugin_safely','list_plugin_checkpoints','restore_plugin_checkpoint','get_backup_schedule','update_backup_schedule','start_backup_job','get_job_status','list_jobs','cancel_job','create_backup','list_backups','get_backup_download_url','delete_backup','list_cron_events','flush_rewrite_rules','clear_cache','get_audit_log','export_audit_log','submit_approval_request','list_approval_requests','execute_approved_request'];
        return [
            'read_only'=>['label'=>'Read-only assistant','short'=>'Safe viewing','description'=>'Can inspect the site, content, SEO and health. Cannot make changes.','scopes'=>['site_read','content_read'],'tools'=>$read,'tone'=>'safe'],
            'content_manager'=>['label'=>'Content manager','short'=>'Pages and media','description'=>'Can manage pages, posts, menus, media and SEO content. Cannot manage plugins, themes or backups.','scopes'=>['site_read','content_read','content_write','media'],'tools'=>$content,'tone'=>'content'],
            'seo_marketing'=>['label'=>'SEO and marketing','short'=>'Visibility tools','description'=>'Can work on content, media, SEO fields, redirects and sitemap visibility without plugin or theme access.','scopes'=>['site_read','content_read','content_write','media','settings'],'tools'=>$seo,'tone'=>'seo'],
            'site_maintenance'=>['label'=>'Site maintenance','short'=>'Operations','description'=>'Can review health, manage private backups and perform controlled plugin and maintenance tasks.','scopes'=>['site_read','plugins','backups','maintenance','audit','settings'],'tools'=>$maintenance,'tone'=>'maintenance'],
            'administrator'=>['label'=>'Full site administrator','short'=>'All curated controls','description'=>'Can use every curated MCP capability. High-impact actions still require confirmation and WordPress permissions.','scopes'=>Xsofty_MCP_Auth::valid_scopes(),'tools'=>[],'tone'=>'danger'],
            'custom'=>['label'=>'Custom access','short'=>'Choose manually','description'=>'Choose capability groups and individual tools yourself. Best for experienced administrators.','scopes'=>[],'tools'=>[],'tone'=>'custom'],
        ];
    }

    public static function scope_presets(): array {
        $definitions=self::preset_definitions();$presets=[];
        foreach($definitions as $key=>$definition)if($key!=='custom')$presets[$key]=$definition['scopes'];
        // Keep v0.3 form/API compatibility for previously selected preset keys.
        $presets['developer']=['site_read','content_read','content_write','media','plugins','theme_read','theme_write','settings','maintenance','audit'];
        $presets['backup_operator']=['site_read','backups','audit'];
        return $presets;
    }

    public static function normalize_token_input(array $input, ?int $now=null): array {
        $now=$now??time();$preset=sanitize_key((string)($input['preset']??'read_only'));$definitions=self::preset_definitions();$presets=self::scope_presets();
        $known=array_column(Xsofty_MCP_Tools::definitions(),'name');
        if($preset==='custom'){$scopes=(array)($input['scopes']??[]);$requested_tools=(array)($input['allowed_tools']??[]);}
        elseif(isset($definitions[$preset])){$scopes=$definitions[$preset]['scopes'];$requested_tools=$definitions[$preset]['tools'];}
        else{$scopes=$presets[$preset]??$presets['read_only'];$requested_tools=(array)($input['allowed_tools']??[]);}
        $scopes=array_values(array_unique(array_intersect(Xsofty_MCP_Auth::valid_scopes(),array_map('sanitize_key',$scopes))));$tools=[];
        foreach($requested_tools as $tool){$tool=sanitize_key((string)$tool);if(in_array($tool,$known,true)&&!in_array($tool,$tools,true))$tools[]=$tool;}
        if(array_key_exists('expires_at',$input)){$raw=trim((string)$input['expires_at']);$expires=$raw===''?0:strtotime($raw.' UTC');if($raw!==''&&$expires===false)throw new InvalidArgumentException('Invalid expiry date.');if($expires>$now+365*86400)throw new InvalidArgumentException('Expiry cannot exceed 365 days.');}
        else{$days=max(0,min(365,(int)($input['expiry_days']??0)));$expires=$days?$now+$days*86400:0;}
        return ['name'=>substr(sanitize_text_field((string)($input['name']??'')),0,80),'scopes'=>$scopes,'allowed_tools'=>$tools,'expires_at'=>(int)$expires,'rate_limit'=>max(10,min(600,(int)($input['rate_limit']??120))),'enabled'=>!array_key_exists('enabled',$input)||(bool)$input['enabled']];
    }

    public static function tool_groups(): array {
        $meta=[
            'site_read'=>['label'=>'Site overview','description'=>'General site, SEO and health information.','icon'=>'dashicons-chart-area'],
            'content_read'=>['label'=>'View content and SEO','description'=>'Read pages, posts, terms, menus and SEO information.','icon'=>'dashicons-visibility'],
            'content_write'=>['label'=>'Edit content and navigation','description'=>'Create, update, restore and remove editorial content.','icon'=>'dashicons-edit-page'],
            'media'=>['label'=>'Media library','description'=>'View and update images and attachment information.','icon'=>'dashicons-format-image'],
            'plugins'=>['label'=>'Plugins','description'=>'Controlled WordPress.org installs, updates and rollback checkpoints.','icon'=>'dashicons-admin-plugins'],
            'theme_read'=>['label'=>'View theme files','description'=>'Inspect files in the active theme without changing them.','icon'=>'dashicons-editor-code'],
            'theme_write'=>['label'=>'Edit safe theme assets','description'=>'Patch non-executable CSS, JSON, TXT and MD files only.','icon'=>'dashicons-art'],
            'settings'=>['label'=>'Settings, redirects and schedules','description'=>'Change approved settings, redirects and backup schedules.','icon'=>'dashicons-admin-settings'],
            'backups'=>['label'=>'Private backups','description'=>'Create, inspect, download and remove private site backups.','icon'=>'dashicons-database'],
            'maintenance'=>['label'=>'Maintenance','description'=>'Inspect scheduled tasks, clear caches and refresh rewrite rules.','icon'=>'dashicons-admin-tools'],
            'audit'=>['label'=>'Activity and approvals','description'=>'Review activity, request approval and execute approved work.','icon'=>'dashicons-yes-alt'],
        ];
        foreach($meta as &$group)$group['tools']=[];unset($group);
        foreach(Xsofty_MCP_Tools::definitions() as $tool)if(isset($meta[$tool['scope']]))$meta[$tool['scope']]['tools'][]=$tool;
        return $meta;
    }

    private static function friendly_tool_name(string $name):string {
        $manual=['site_info'=>'View site overview','get_site_health'=>'Review site health','get_seo_status'=>'Review SEO setup','get_sitemap_status'=>'Review sitemap status','list_cron_events'=>'View scheduled tasks','run_cron_event'=>'Run a scheduled task','flush_rewrite_rules'=>'Refresh website links','clear_cache'=>'Clear site cache','update_plugin_safely'=>'Update a plugin with rollback','get_backup_download_url'=>'Create a secure download link','submit_approval_request'=>'Request administrator approval','execute_approved_request'=>'Run approved work','get_audit_log'=>'View activity history','export_audit_log'=>'Export activity history'];
        if(isset($manual[$name]))return $manual[$name];
        $verbs=['get_'=>'View ','list_'=>'List ','create_'=>'Create ','update_'=>'Update ','delete_'=>'Delete ','restore_'=>'Restore ','set_'=>'Set ','upload_'=>'Upload ','install_'=>'Install ','activate_'=>'Activate ','deactivate_'=>'Deactivate ','start_'=>'Start ','cancel_'=>'Cancel ','upsert_'=>'Create or update ','read_'=>'Read ','patch_'=>'Edit ','export_'=>'Export '];
        foreach($verbs as $prefix=>$verb)if(str_starts_with($name,$prefix))return $verb.ucfirst(str_replace('_',' ',substr($name,strlen($prefix))));
        return ucfirst(str_replace('_',' ',$name));
    }

    public static function init(): void {
        add_action('admin_menu',[self::class,'menu']);add_action('admin_enqueue_scripts',[self::class,'assets']);
        add_action('admin_post_xsofty_mcp_save',[self::class,'save']);add_action('admin_post_xsofty_mcp_generate',[self::class,'generate']);add_action('admin_post_xsofty_mcp_token_create',[self::class,'create_token']);add_action('admin_post_xsofty_mcp_token_update',[self::class,'update_token']);add_action('admin_post_xsofty_mcp_token_revoke',[self::class,'revoke_token']);add_action('admin_post_xsofty_mcp_revoke',[self::class,'revoke']);
        if(defined('WP_CLI')&&WP_CLI)Xsofty_MCP_CLI::register();
    }

    public static function menu(): void {add_options_page('Xsofty WordPress MCP','Xsofty MCP','manage_options','xsofty-wordpress-mcp',[self::class,'page']);}
    public static function assets(string $hook):void {if($hook!=='settings_page_xsofty-wordpress-mcp')return;$base=plugin_dir_url(XSOFTY_WP_MCP_FILE);wp_enqueue_style('dashicons');wp_enqueue_style('xsofty-mcp-admin',$base.'assets/admin.css',[],XSOFTY_WP_MCP_VERSION);wp_enqueue_script('xsofty-mcp-admin',$base.'assets/admin.js',[],XSOFTY_WP_MCP_VERSION,true);}
    private static function require_admin():void {if(!current_user_can('manage_options'))wp_die('You do not have permission to manage MCP access.');}
    private static function redirect(array $args=[]):void {wp_safe_redirect(add_query_arg(array_merge(['page'=>'xsofty-wordpress-mcp'],$args),admin_url('options-general.php')));exit;}
    private static function render_token_once(array $created):void {nocache_headers();header('X-Frame-Options: DENY');$back=admin_url('options-general.php?page=xsofty-wordpress-mcp');$message='<div style="max-width:720px;margin:32px auto;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif"><h1>Connection created</h1><p><strong>Copy this access token now. It will not be shown again.</strong></p><p><code style="display:block;padding:16px;border:1px solid #c3c4c7;background:#fff;word-break:break-all">'.esc_html((string)$created['token']).'</code></p><p>Store it in a password manager or protected environment file. Never paste it into a public document.</p><p><a class="button button-primary" href="'.esc_url($back).'">Return to MCP control center</a></p></div>';wp_die($message,'MCP connection created',['response'=>200,'back_link'=>false]);}
    private static function nonce_field(string $action):void {echo '<input type="hidden" name="_wpnonce" value="'.esc_attr(wp_create_nonce($action)).'">';}

    public static function save():void {
        self::require_admin();check_admin_referer('xsofty_mcp_save');$backup=Xsofty_MCP_Jobs::normalize_schedule((string)($_POST['backup_schedule']??'disabled'),(int)($_POST['backup_retention']??5));
        $origins=preg_split('/\r\n|\r|\n/',(string)($_POST['allowed_origins']??''));$origins=array_values(array_filter(array_map(static function($origin){$origin=untrailingslashit(esc_url_raw(trim($origin)));return str_starts_with($origin,'https://')?$origin:'';},$origins)));
        $known=array_column(Xsofty_MCP_Tools::definitions(),'name');$enabled=array_values(array_intersect($known,array_map('sanitize_key',(array)($_POST['enabled_tools']??[]))));$disabled=array_values(array_diff($known,$enabled));
        try{Xsofty_MCP_Auth::update_settings(function(array $settings)use($origins,$disabled):array {$settings['enabled']=isset($_POST['enabled']);$settings['allow_http']=isset($_POST['allow_http']);$settings['allow_cron_run']=isset($_POST['allow_cron_run']);$settings['rate_limit']=max(10,min(600,(int)($_POST['rate_limit']??120)));$settings['allowed_origins']=$origins;$settings['disabled_tools']=$disabled;return $settings;});Xsofty_MCP_Jobs::update_schedule($backup['schedule'],$backup['retention']);Xsofty_MCP_Auth::audit('settings_updated',true);self::redirect(['updated'=>'1']);}
        catch(Throwable $error){Xsofty_MCP_Auth::audit('settings_updated',false,['error'=>substr($error->getMessage(),0,160)]);self::redirect(['error'=>rawurlencode(substr($error->getMessage(),0,160))]);}
    }

    public static function create_token():void {self::require_admin();check_admin_referer('xsofty_mcp_token_create');$input=self::normalize_token_input(wp_unslash($_POST));try{$created=Xsofty_MCP_Auth::create_token($input['name'],get_current_user_id(),$input['scopes'],$input['expires_at'],$input['allowed_tools']);Xsofty_MCP_Auth::update_token($created['id'],['rate_limit'=>$input['rate_limit'],'enabled'=>true]);self::render_token_once($created);}catch(Throwable $error){self::redirect(['error'=>rawurlencode(substr($error->getMessage(),0,160))]);}}
    public static function generate():void {self::create_token();}
    public static function update_token():void {self::require_admin();check_admin_referer('xsofty_mcp_token_update');$id=sanitize_key((string)($_POST['token_id']??''));$input=self::normalize_token_input(wp_unslash($_POST));try{if(!Xsofty_MCP_Auth::update_token($id,$input))throw new RuntimeException('Connection not found.');self::redirect(['updated'=>'1']);}catch(Throwable $error){self::redirect(['error'=>rawurlencode(substr($error->getMessage(),0,160))]);}}
    public static function revoke_token():void {self::require_admin();check_admin_referer('xsofty_mcp_token_revoke');$id=sanitize_key((string)($_POST['token_id']??''));if($id!=='')Xsofty_MCP_Auth::revoke_token($id);self::redirect(['revoked'=>'1']);}
    public static function revoke():void {self::require_admin();check_admin_referer('xsofty_mcp_revoke');Xsofty_MCP_Auth::revoke();self::redirect(['revoked'=>'1']);}

    private static function scope_labels():array {return ['site_read'=>'Site overview','content_read'=>'View content and SEO','content_write'=>'Edit content and navigation','media'=>'Media library','plugins'=>'Plugin operations','theme_read'=>'View active-theme files','theme_write'=>'Edit safe theme assets','settings'=>'Settings, redirects and schedules','backups'=>'Private backups','maintenance'=>'Maintenance actions','audit'=>'Activity and approvals'];}
    private static function scope_summary(array $scopes):string {$labels=self::scope_labels();$names=[];foreach($scopes as $scope)if(isset($labels[$scope]))$names[]=$labels[$scope];return implode(', ',$names);}

    private static function preset_picker(string $selected):void {?>
        <fieldset class="xwmcp-fieldset xwmcp-preset-picker"><legend>Choose an access preset</legend><p class="xwmcp-help">Start with a safe role. You can choose Custom access for precise control.</p><div class="xwmcp-preset-grid">
        <?php foreach(self::preset_definitions() as $key=>$preset): ?><label class="xwmcp-preset xwmcp-preset--<?php echo esc_attr($preset['tone']); ?>"><input type="radio" name="preset" value="<?php echo esc_attr($key); ?>" <?php checked($selected,$key); ?>><span class="xwmcp-preset__check" aria-hidden="true"></span><strong><?php echo esc_html($preset['label']); ?></strong><span><?php echo esc_html($preset['description']); ?></span></label><?php endforeach; ?>
        </div><p class="xwmcp-preset-summary" data-preset-summary aria-live="polite"></p></fieldset><?php
    }

    private static function scope_picker(array $scopes):void {?>
        <fieldset class="xwmcp-fieldset" data-custom-permissions><legend>Capability groups</legend><p class="xwmcp-help">Capabilities are broad permission areas. Presets select these automatically.</p><div class="xwmcp-check-grid">
        <?php foreach(self::scope_labels() as $key=>$label): ?><label class="xwmcp-check"><input type="checkbox" name="scopes[]" value="<?php echo esc_attr($key); ?>" <?php checked(in_array($key,$scopes,true)); ?>><span><strong><?php echo esc_html($label); ?></strong><small><?php echo esc_html(self::tool_groups()[$key]['description']); ?></small></span></label><?php endforeach; ?>
        </div></fieldset><?php
    }

    private static function tool_picker(array $allowed,bool $global=false,array $disabled=[]):void {?>
        <div class="xwmcp-tools" data-tool-picker><div class="xwmcp-tools__bar"><label><span class="screen-reader-text">Search tools</span><input type="search" class="xwmcp-tool-search" placeholder="Search capabilities or technical names"></label><span class="xwmcp-tool-count" aria-live="polite"></span></div>
        <?php foreach(self::tool_groups() as $scope=>$group): ?><details class="xwmcp-tool-group" data-tool-group><summary><span class="dashicons <?php echo esc_attr($group['icon']); ?>" aria-hidden="true"></span><span><strong><?php echo esc_html($group['label']); ?></strong><small><?php echo esc_html($group['description']); ?></small></span><span class="xwmcp-count"><?php echo esc_html((string)count($group['tools'])); ?></span></summary><div class="xwmcp-tool-list">
        <?php foreach($group['tools'] as $tool): $checked=$global?!in_array($tool['name'],$disabled,true):in_array($tool['name'],$allowed,true); ?><label class="xwmcp-tool" data-tool-search-text="<?php echo esc_attr(strtolower(self::friendly_tool_name($tool['name']).' '.$tool['name'].' '.$tool['description'])); ?>"><input type="checkbox" name="<?php echo $global?'enabled_tools':'allowed_tools'; ?>[]" value="<?php echo esc_attr($tool['name']); ?>" <?php checked($checked); ?>><span><strong><?php echo esc_html(self::friendly_tool_name($tool['name'])); ?></strong><small><?php echo esc_html($tool['description']); ?></small><code><?php echo esc_html($tool['name']); ?></code></span></label><?php endforeach; ?>
        </div></details><?php endforeach; ?></div><?php
    }

    private static function token_form(array $record=[]):void {
        $editing=!empty($record);$id=(string)($record['id']??'');$scopes=(array)($record['scopes']??self::scope_presets()['read_only']);$allowed=(array)($record['allowed_tools']??self::preset_definitions()['read_only']['tools']);$expires=(int)($record['expires_at']??0);$expiry_value=$expires?gmdate('Y-m-d\TH:i',$expires):'';$selected=$editing?'custom':'read_only';
        ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="xwmcp-connection-form" data-connection-form>
        <input type="hidden" name="action" value="<?php echo esc_attr($editing?'xsofty_mcp_token_update':'xsofty_mcp_token_create'); ?>"><?php if($editing): ?><input type="hidden" name="token_id" value="<?php echo esc_attr($id); ?>"><?php endif; ?><?php self::nonce_field($editing?'xsofty_mcp_token_update':'xsofty_mcp_token_create'); ?>
        <div class="xwmcp-form-grid"><label class="xwmcp-field"><span>Connection name</span><input class="regular-text" required maxlength="80" name="name" placeholder="For example: Content team" value="<?php echo esc_attr($record['name']??''); ?>"><small>Use a name that identifies the person, team or assistant.</small></label><label class="xwmcp-field"><span>Expiry</span><input type="datetime-local" name="expires_at" value="<?php echo esc_attr($expiry_value); ?>"><small>UTC. Leave blank for no automatic expiry.</small></label><label class="xwmcp-field"><span>Request limit</span><span class="xwmcp-input-unit"><input type="number" min="10" max="600" name="rate_limit" value="<?php echo esc_attr($record['rate_limit']??120); ?>"><em>per minute</em></span><small>Protects the site from excessive requests.</small></label><?php if($editing): ?><label class="xwmcp-field"><span>Connection status</span><span class="xwmcp-switch-row"><input type="checkbox" name="enabled" value="1" <?php checked(!empty($record['enabled'])); ?>><strong>Enabled</strong></span><small>Disable temporarily without revoking the token.</small></label><?php endif; ?></div>
        <?php self::preset_picker($selected);self::scope_picker($scopes); ?><details class="xwmcp-advanced" data-advanced-tools><summary>Customize individual tools <span>Advanced</span></summary><p class="xwmcp-help">With Custom access, leave every tool unchecked to allow every tool covered by the selected capability groups.</p><?php self::tool_picker($allowed); ?></details>
        <div class="xwmcp-form-actions"><?php submit_button($editing?'Save connection':'Create secure connection',$editing?'secondary':'primary','submit',false,['id'=>$editing?'xwmcp-save-connection-'.$id:'xwmcp-create-connection']); ?><span>Changes are validated against WordPress permissions when used.</span></div></form><?php
    }

    private static function connection_card(array $record):void {$expires=(int)($record['expires_at']??0);$expired=$expires&&$expires<time();$enabled=!empty($record['enabled'])&&!$expired;$last=(int)($record['last_used_at']??0);?>
        <article class="xwmcp-connection-card"><div class="xwmcp-connection-card__head"><div><span class="xwmcp-status xwmcp-status--<?php echo $enabled?'good':'muted'; ?>"><i aria-hidden="true"></i><?php echo $expired?'Expired':($enabled?'Active':'Disabled'); ?></span><h3><?php echo esc_html((string)$record['name']); ?></h3><p><?php echo esc_html(self::scope_summary((array)$record['scopes'])); ?></p></div><span class="dashicons dashicons-admin-network" aria-hidden="true"></span></div><dl><div><dt>Expires</dt><dd><?php echo $expires?esc_html(gmdate('M j, Y',$expires).' UTC'):'Never'; ?></dd></div><div><dt>Last used</dt><dd><?php echo $last?esc_html(human_time_diff($last,time()).' ago'):'Not yet'; ?></dd></div><div><dt>Tool access</dt><dd><?php $count=count((array)($record['allowed_tools']??[]));echo $count?esc_html($count.' selected'):'All within capabilities'; ?></dd></div></dl>
        <details class="xwmcp-manage"><summary>Manage connection</summary><?php self::token_form($record); ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="xwmcp-revoke" onsubmit="return confirm('Permanently revoke this connection? The existing token will stop working immediately.');"><input type="hidden" name="action" value="xsofty_mcp_token_revoke"><input type="hidden" name="token_id" value="<?php echo esc_attr($record['id']); ?>"><?php self::nonce_field('xsofty_mcp_token_revoke');submit_button('Revoke permanently','delete','submit',false,['id'=>'xwmcp-revoke-connection-'.$record['id']]);?></form></details></article><?php
    }

    public static function page():void {
        self::require_admin();$settings=Xsofty_MCP_Auth::settings();$records=Xsofty_MCP_Auth::token_records();$known=array_column(Xsofty_MCP_Tools::definitions(),'name');$disabled=(array)($settings['disabled_tools']??[]);$active=count(array_filter($records,static fn($r)=>!empty($r['enabled'])&&(!(int)($r['expires_at']??0)||(int)$r['expires_at']>=time())));$schedule=Xsofty_MCP_Jobs::schedule_settings();$enabled_count=count(array_diff($known,$disabled));$preset_data=[];foreach(self::preset_definitions() as $key=>$preset)$preset_data[$key]=['label'=>$preset['label'],'description'=>$preset['description'],'scopes'=>$preset['scopes'],'tools'=>$preset['tools']];
        ?><div class="wrap xwmcp-wrap"><script type="application/json" id="xwmcp-preset-data"><?php echo wp_json_encode($preset_data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE); ?></script>
        <header class="xwmcp-hero"><div><span class="xwmcp-eyebrow">Xsofty WordPress MCP</span><h1>AI access, under your control.</h1><p>Connect trusted assistants to WordPress without exposing passwords, server access or unrestricted code execution.</p></div><div class="xwmcp-hero__state"><span class="xwmcp-status xwmcp-status--<?php echo !empty($settings['enabled'])?'good':'muted'; ?>"><i aria-hidden="true"></i><?php echo !empty($settings['enabled'])?'Bridge enabled':'Bridge paused'; ?></span><small>Version <?php echo esc_html(XSOFTY_WP_MCP_VERSION); ?></small></div></header>
        <?php if(!empty($_GET['error'])): ?><div class="notice notice-error"><p><?php echo esc_html(sanitize_text_field(wp_unslash($_GET['error']))); ?></p></div><?php elseif(!empty($_GET['updated'])): ?><div class="notice notice-success is-dismissible"><p>Settings saved.</p></div><?php elseif(!empty($_GET['revoked'])): ?><div class="notice notice-success is-dismissible"><p>Connection revoked.</p></div><?php endif; ?>
        <nav class="xwmcp-nav" aria-label="MCP settings sections"><a href="#xwmcp-overview">Overview</a><a href="#xwmcp-connections">Connections</a><a href="#xwmcp-controls">Safety and tools</a><a href="#xwmcp-activity">Activity</a><a href="#xwmcp-connect">Setup</a></nav>

        <section id="xwmcp-overview" class="xwmcp-section"><div class="xwmcp-section__head"><div><span class="xwmcp-kicker">Overview</span><h2>Everything important at a glance</h2></div></div><div class="xwmcp-stat-grid"><article><span class="dashicons dashicons-admin-network" aria-hidden="true"></span><strong><?php echo esc_html((string)$active); ?></strong><small>Active connections</small></article><article><span class="dashicons dashicons-admin-tools" aria-hidden="true"></span><strong><?php echo esc_html($enabled_count.' / '.count($known)); ?></strong><small>Tools available globally</small></article><article><span class="dashicons dashicons-backup" aria-hidden="true"></span><strong><?php echo esc_html(ucfirst($schedule['schedule'])); ?></strong><small>Backup schedule</small></article><article><span class="dashicons dashicons-shield" aria-hidden="true"></span><strong><?php echo is_ssl()?'HTTPS':(!empty($settings['allow_http'])?'Local HTTP':'HTTP blocked'); ?></strong><small>Connection protection</small></article></div><div class="xwmcp-endpoint"><div><span>MCP endpoint</span><code id="xwmcp-endpoint-value"><?php echo esc_html(rest_url('xsofty-mcp/v1/mcp')); ?></code></div><button type="button" class="button" data-copy-target="xwmcp-endpoint-value"><span class="dashicons dashicons-admin-page" aria-hidden="true"></span> Copy endpoint</button></div></section>

        <section id="xwmcp-connections" class="xwmcp-section"><div class="xwmcp-section__head"><div><span class="xwmcp-kicker">Connections</span><h2>Who can access this site?</h2><p>Every person or assistant receives a separate, revocable connection with only the access it needs.</p></div><span class="xwmcp-section__metric"><?php echo esc_html((string)count($records)); ?> configured</span></div><?php if(!$records): ?><div class="xwmcp-empty"><span class="dashicons dashicons-lock" aria-hidden="true"></span><h3>No connections yet</h3><p>Create a read-only connection to start safely.</p></div><?php else: ?><div class="xwmcp-connection-grid"><?php foreach($records as $record)self::connection_card($record); ?></div><?php endif; ?><details class="xwmcp-create" <?php echo !$records?'open':''; ?>><summary><span class="dashicons dashicons-plus-alt2" aria-hidden="true"></span><span><strong>Create a new connection</strong><small>Choose a preset, name it, then copy the one-time token.</small></span></summary><?php self::token_form(); ?></details></section>

        <section id="xwmcp-controls" class="xwmcp-section"><div class="xwmcp-section__head"><div><span class="xwmcp-kicker">Safety and tools</span><h2>Site-wide guardrails</h2><p>These controls apply to every connection. Individual access can only become more restricted, never broader.</p></div></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="xwmcp-global-form"><input type="hidden" name="action" value="xsofty_mcp_save"><?php self::nonce_field('xsofty_mcp_save'); ?>
        <div class="xwmcp-settings-grid"><article class="xwmcp-settings-card"><div class="xwmcp-card-title"><span class="dashicons dashicons-controls-play" aria-hidden="true"></span><div><h3>Bridge availability</h3><p>Pause every MCP connection without deleting it.</p></div></div><label class="xwmcp-toggle"><input type="checkbox" name="enabled" value="1" <?php checked($settings['enabled']); ?>><span aria-hidden="true"></span><strong>Allow MCP connections</strong></label><label class="xwmcp-field"><span>Default request limit</span><span class="xwmcp-input-unit"><input type="number" min="10" max="600" name="rate_limit" value="<?php echo esc_attr($settings['rate_limit']); ?>"><em>per minute</em></span><small>Individual connections can use a lower or higher bounded limit.</small></label></article>
        <article class="xwmcp-settings-card"><div class="xwmcp-card-title"><span class="dashicons dashicons-backup" aria-hidden="true"></span><div><h3>Scheduled private backups</h3><p>Backups stay outside the public website directory.</p></div></div><div class="xwmcp-inline-fields"><label class="xwmcp-field"><span>Schedule</span><select name="backup_schedule"><option value="disabled" <?php selected($settings['backup_schedule']??'disabled','disabled'); ?>>Off</option><option value="daily" <?php selected($settings['backup_schedule']??'disabled','daily'); ?>>Every day</option><option value="weekly" <?php selected($settings['backup_schedule']??'disabled','weekly'); ?>>Every week</option></select></label><label class="xwmcp-field"><span>Keep</span><span class="xwmcp-input-unit"><input type="number" min="1" max="20" name="backup_retention" value="<?php echo esc_attr((int)($settings['backup_retention']??5)); ?>"><em>backups</em></span></label></div><p class="xwmcp-callout"><span class="dashicons dashicons-info-outline" aria-hidden="true"></span>Complete backups contain site files and database content. Give backup access only to trusted administrators.</p></article></div>
        <article class="xwmcp-settings-card xwmcp-settings-card--wide"><div class="xwmcp-card-title"><span class="dashicons dashicons-shield-alt" aria-hidden="true"></span><div><h3>High-impact actions</h3><p>Keep uncommon or sensitive operations off unless they are required.</p></div></div><div class="xwmcp-guardrails"><label class="xwmcp-toggle"><input type="checkbox" name="allow_cron_run" value="1" <?php checked(!empty($settings['allow_cron_run'])); ?>><span aria-hidden="true"></span><strong>Allow manual scheduled-task runs</strong><small>Only existing registered events can run; arguments are never exposed.</small></label><label class="xwmcp-toggle"><input type="checkbox" name="allow_http" value="1" <?php checked($settings['allow_http']); ?>><span aria-hidden="true"></span><strong>Allow unencrypted local connections</strong><small>Works only on loopback, private-network or <code>.local</code> hosts. Live sites require HTTPS.</small></label></div><details class="xwmcp-advanced"><summary>Browser origin allowlist <span>Advanced</span></summary><label class="xwmcp-field"><span>Approved browser applications</span><textarea name="allowed_origins" rows="4" class="large-text code" placeholder="https://control.example.com"><?php echo esc_textarea(implode("\n",(array)$settings['allowed_origins'])); ?></textarea><small>Optional HTTPS origins, one per line. Normal non-browser MCP clients do not send an Origin header.</small></label></details></article>
        <article class="xwmcp-settings-card xwmcp-settings-card--wide"><div class="xwmcp-card-title xwmcp-card-title--tools"><span class="dashicons dashicons-admin-generic" aria-hidden="true"></span><div><h3>Globally available tools</h3><p>Disable a tool here to remove it from every connection immediately.</p></div><span class="xwmcp-section__metric"><?php echo esc_html($enabled_count.' enabled'); ?></span></div><div class="xwmcp-quick-presets"><span>Quick setup</span><button type="button" class="button" data-global-preset="read_only">Viewing only</button><button type="button" class="button" data-global-preset="content_manager">Content work</button><button type="button" class="button" data-global-preset="site_maintenance">Maintenance</button><button type="button" class="button" data-global-preset="administrator">Enable all</button></div><?php self::tool_picker([],true,$disabled); ?></article>
        <div class="xwmcp-savebar"><div><strong>Review before saving</strong><span>Changes affect every connection on this site.</span></div><?php submit_button('Save site-wide settings','primary','submit',false,['id'=>'xwmcp-save-site-settings']); ?></div></form></section>

        <section id="xwmcp-activity" class="xwmcp-section"><div class="xwmcp-section__head"><div><span class="xwmcp-kicker">Activity</span><h2>Administrator approvals</h2><p>Review sensitive requests before an assistant can execute them.</p></div></div><div class="xwmcp-activity-card"><?php Xsofty_MCP_Control::render_admin(); ?></div></section>

        <section id="xwmcp-connect" class="xwmcp-section"><div class="xwmcp-section__head"><div><span class="xwmcp-kicker">Setup</span><h2>Connect Hermes securely</h2><p>Store the one-time token in an environment variable. Never paste a real token into configuration files or source control.</p></div></div><div class="xwmcp-code-card"><div><span>Hermes configuration</span><button type="button" class="button button-small" data-copy-target="xwmcp-hermes-code">Copy example</button></div><pre id="xwmcp-hermes-code">mcp_servers:
  wordpress-site:
    url: <?php echo esc_html(rest_url('xsofty-mcp/v1/mcp')); ?>
    headers:
      Authorization: "Bearer ${WORDPRESS_MCP_TOKEN}"
    enabled: true</pre></div><ol class="xwmcp-steps"><li><strong>Create a connection</strong><span>Choose the least powerful preset that can do the job.</span></li><li><strong>Copy the token once</strong><span>Store it in a protected environment variable or password manager.</span></li><li><strong>Add the endpoint</strong><span>Use the example above, then test connection and tool discovery.</span></li></ol></section>
        </div><?php
    }
}

if(defined('WP_CLI')&&WP_CLI){
    final class Xsofty_MCP_CLI {
        public static function register():void{WP_CLI::add_command('xsofty-mcp',self::class);}
        /** Create, list or revoke named MCP tokens. */
        public function token(array $args,array $assoc):void{$action=$args[0]??'create';if($action==='create'){$name=sanitize_text_field($assoc['name']??'CLI connection');$days=max(0,min(365,(int)($assoc['expires']??0)));$scopes=isset($assoc['scopes'])?explode(',',(string)$assoc['scopes']):null;$tools=isset($assoc['tools'])?explode(',',(string)$assoc['tools']):[];$created=Xsofty_MCP_Auth::create_token($name,0,$scopes,$days?time()+$days*86400:0,$tools);WP_CLI::line('TOKEN_ID='.$created['id']);WP_CLI::line('TOKEN='.$created['token']);return;}if($action==='list'){$items=[];foreach(Xsofty_MCP_Auth::token_records() as $r){unset($r['token_hash'],$r['download_key']);$items[]=$r;}WP_CLI::line(wp_json_encode($items,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));return;}if($action==='revoke'){$id=sanitize_key($args[1]??'');if($id===''||!Xsofty_MCP_Auth::revoke_token($id))WP_CLI::error('Token not found.');WP_CLI::success('MCP token revoked.');return;}WP_CLI::error('Use: wp xsofty-mcp token create|list|revoke <id>');}
        /** Show bridge status without revealing credentials. */
        public function status():void{$s=Xsofty_MCP_Auth::settings();WP_CLI::line(wp_json_encode(['enabled'=>(bool)$s['enabled'],'connections'=>count(Xsofty_MCP_Auth::token_records()),'endpoint'=>rest_url('xsofty-mcp/v1/mcp'),'globally_disabled_tools'=>(array)$s['disabled_tools']],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));}
        /** Create a complete local backup. */
        public function backup(array $args,array $assoc):void{$result=Xsofty_MCP_Backups::create(sanitize_text_field($assoc['label']??'cli'));WP_CLI::line(wp_json_encode($result,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));}
    }
}
