<?php
if(!defined('ABSPATH'))exit;

final class Xsofty_MCP_Control {
    public const APPROVAL_OPTION='xsofty_mcp_approval_queue';
    private const LOCK_OPTION='xsofty_mcp_approval_lock';

    public static function init():void {add_action('admin_post_xsofty_mcp_approval',[self::class,'admin_decide']);}

    public static function sanitize_request_arguments(array $arguments,int $depth=0):array {if($depth>5||count($arguments)>50)throw new InvalidArgumentException('Approval arguments exceed nesting or item limits.');$clean=[];foreach($arguments as $key=>$value){$key=(string)$key;if(preg_match('/authorization|token|secret|password|cookie|api_?key|credential/i',$key))throw new InvalidArgumentException('Sensitive fields cannot be stored in approval requests.');if(is_array($value))$clean[$key]=self::sanitize_request_arguments($value,$depth+1);elseif(is_string($value)){$text=function_exists('wp_check_invalid_utf8')?wp_check_invalid_utf8($value):$value;$clean[$key]=substr($text,0,20000);}elseif(is_int($value)||is_float($value)||is_bool($value)||$value===null)$clean[$key]=$value;else throw new InvalidArgumentException('Approval arguments must contain JSON-compatible values only.');}if(strlen((string)wp_json_encode($clean))>32768)throw new InvalidArgumentException('Approval arguments exceed 32 KB.');return $clean;}

    private static function lock():string {$token=bin2hex(random_bytes(8));$value=['token'=>$token,'expires'=>time()+30];if(add_option(self::LOCK_OPTION,$value,'','no'))return $token;$old=get_option(self::LOCK_OPTION);if(is_array($old)&&(int)($old['expires']??0)<time()){delete_option(self::LOCK_OPTION);if(add_option(self::LOCK_OPTION,$value,'','no'))return $token;}throw new RuntimeException('Another approval operation is in progress.');}
    private static function unlock(string $token):void {$value=get_option(self::LOCK_OPTION);if(is_array($value)&&hash_equals((string)($value['token']??''),$token))delete_option(self::LOCK_OPTION);}
    private static function records():array {return (array)get_option(self::APPROVAL_OPTION,[]);}
    private static function canonicalize($value){if(!is_array($value))return $value;if(!array_is_list($value))ksort($value,SORT_STRING);foreach($value as $key=>$child)$value[$key]=self::canonicalize($child);return $value;}
    private static function arguments_hash(array $arguments):string {return hash('sha256',(string)wp_json_encode(self::canonicalize($arguments),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}
    private static function plan_hash(string $tool,array $arguments,array $schema):string {return hash('sha256',$tool."\n".(string)wp_json_encode(self::canonicalize($arguments),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n".(string)wp_json_encode(self::canonicalize($schema),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}
    private static function mutate(callable $callback){$lock=self::lock();try{$records=self::records();foreach($records as &$record){if(($record['status']??'')==='pending'&&(int)($record['expires_at']??0)<time())$record['status']='expired';if(($record['status']??'')==='executing'&&!empty($record['executing_at'])&&strtotime((string)$record['executing_at'])<time()-2*HOUR_IN_SECONDS){$record['status']='failed';$record['error']='Execution state expired; outcome requires manual verification.';}}unset($record);$result=$callback($records);uasort($records,static fn($a,$b)=>strcmp($b['created_at'],$a['created_at']));$records=array_slice($records,0,100,true);update_option(self::APPROVAL_OPTION,$records,false);return $result;}finally{self::unlock($lock);}}
    private static function public_record(array $record):array {return $record;}

    public static function submit(string $tool,array $arguments,string $summary):array {$tool=sanitize_key($tool);if(in_array($tool,['submit_approval_request','execute_approved_request'],true))throw new InvalidArgumentException('Approval tools cannot approve themselves.');$definition=Xsofty_MCP_Tools::definition($tool);if(!$definition)throw new InvalidArgumentException('Unknown target tool.');if(!empty($definition['annotations']['readOnlyHint']))throw new InvalidArgumentException('Read-only tools do not require approval.');if(!Xsofty_MCP_Auth::has_scope($definition['scope'])||!Xsofty_MCP_Auth::tool_allowed($tool))throw new RuntimeException('The active token cannot request this tool.');$arguments=self::sanitize_request_arguments($arguments);$arguments['confirm']=true;$errors=Xsofty_MCP_Server::validate_arguments($definition['inputSchema'],$arguments);if($errors)throw new InvalidArgumentException('Target arguments are invalid: '.implode('; ',$errors));$token=Xsofty_MCP_Auth::active_token_id();if($token==='')throw new RuntimeException('An authenticated named token is required.');$id=bin2hex(random_bytes(12));$record=['id'=>$id,'tool'=>$tool,'summary'=>substr(sanitize_text_field($summary),0,200),'arguments'=>$arguments,'arguments_sha256'=>self::arguments_hash($arguments),'plan_sha256'=>self::plan_hash($tool,$arguments,$definition['inputSchema']),'token_id'=>$token,'actor'=>(int)get_current_user_id(),'status'=>'pending','created_at'=>gmdate('c'),'expires_at'=>time()+DAY_IN_SECONDS,'decided_at'=>null,'executing_at'=>null,'executed_at'=>null];self::mutate(function(array &$records)use($id,$record){$records[$id]=$record;});return self::public_record($record);}

    public static function list_approvals(string $status='all',int $limit=50,bool $admin=false):array {$status=sanitize_key($status);if(!in_array($status,['all','pending','approved','rejected','executing','executed','failed','expired'],true))$status='all';$token=Xsofty_MCP_Auth::active_token_id();$items=[];foreach(self::records() as $record){if(!$admin&&($token===''||!hash_equals((string)$record['token_id'],$token)))continue;if($status!=='all'&&($record['status']??'')!==$status)continue;$items[]=self::public_record($record);}return ['items'=>array_slice($items,0,max(1,min(100,$limit))),'count'=>count($items)];}

    public static function decide(string $id,string $decision):array {$id=sanitize_key($id);$decision=sanitize_key($decision);if(!in_array($decision,['approved','rejected'],true))throw new InvalidArgumentException('Decision must be approved or rejected.');$approver=(int)get_current_user_id();$result=self::mutate(function(array &$records)use($id,$decision,$approver){if(!isset($records[$id]))throw new RuntimeException('Approval request not found.');if(($records[$id]['status']??'')!=='pending')throw new RuntimeException('Only pending requests can be decided.');$records[$id]['status']=$decision;$records[$id]['decided_at']=gmdate('c');$records[$id]['decided_by']=$approver;return self::public_record($records[$id]);});Xsofty_MCP_Auth::audit('approval_'.$decision,true,['approval_id'=>$id,'target_tool'=>$result['tool']??'','subject_token_id'=>$result['token_id']??'']);return $result;}

    public static function execute(string $id):array {$id=sanitize_key($id);$token=Xsofty_MCP_Auth::active_token_id();$record=self::mutate(function(array &$records)use($id,$token){if(!isset($records[$id])||$token===''||!hash_equals((string)$records[$id]['token_id'],$token))throw new RuntimeException('Approval request not found.');if(($records[$id]['status']??'')!=='approved')throw new RuntimeException('Approval request is not approved.');$approver=(int)($records[$id]['decided_by']??0);if($approver<1||!get_user_by('id',$approver)||!user_can($approver,'manage_options'))throw new RuntimeException('Approval administrator is no longer authorized.');if((int)$records[$id]['expires_at']<time()){$records[$id]['status']='expired';throw new RuntimeException('Approval request expired.');}$definition=Xsofty_MCP_Tools::definition((string)$records[$id]['tool']);if(!$definition||!hash_equals((string)($records[$id]['arguments_sha256']??''),self::arguments_hash((array)$records[$id]['arguments']))||!hash_equals((string)($records[$id]['plan_sha256']??''),self::plan_hash((string)$records[$id]['tool'],(array)$records[$id]['arguments'],$definition['inputSchema'])))throw new RuntimeException('Approval plan integrity validation failed.');$records[$id]['status']='executing';$records[$id]['executing_at']=gmdate('c');return $records[$id];});$definition=Xsofty_MCP_Tools::definition($record['tool']);if(!$definition||!Xsofty_MCP_Auth::has_scope($definition['scope'])||!Xsofty_MCP_Auth::tool_allowed($record['tool'])){$status='failed';$error='The approved target is no longer available to this token.';}else{try{$result=Xsofty_MCP_Tools::call($record['tool'],$record['arguments']);if(!empty($result['isError']))throw new RuntimeException(substr((string)($result['content'][0]['text']??'Approved target failed.'),0,180));$status='executed';$error='';}catch(Throwable $e){$status='failed';$error=substr(sanitize_text_field($e->getMessage()),0,180);}}self::mutate(function(array &$records)use($id,$status,$error){if(isset($records[$id])){$records[$id]['status']=$status;$records[$id]['executed_at']=gmdate('c');if($error!=='')$records[$id]['error']=$error;}});if($status!=='executed')throw new RuntimeException($error);return ['approval_id'=>$id,'tool'=>$record['tool'],'executed'=>true,'result'=>$result];}

    public static function query_audit(array $filters):array {$limit=max(1,min(500,(int)($filters['limit']??50)));$action=sanitize_key((string)($filters['action']??''));$token=sanitize_key((string)($filters['token_id']??''));$success=array_key_exists('success',$filters)?(bool)$filters['success']:null;$since=isset($filters['since'])?strtotime((string)$filters['since']):false;$items=[];foreach(array_reverse((array)get_option(Xsofty_MCP_Auth::AUDIT_KEY,[])) as $row){if($action!==''&&($row['action']??'')!==$action)continue;if($token!==''&&($row['token_id']??'')!==$token&&($row['subject_token_id']??'')!==$token)continue;if($success!==null&&(bool)($row['success']??false)!==$success)continue;if($since!==false&&strtotime((string)($row['time']??''))<$since)continue;$items[]=$row;if(count($items)>=$limit)break;}return ['items'=>$items,'count'=>count($items)];}

    public static function export_audit(array $filters):array {$data=self::query_audit($filters);$stream=fopen('php://temp','w+');fputcsv($stream,['time','action','success','site','actor','token_id','subject_token_id','remote','context']);foreach($data['items'] as $row)fputcsv($stream,[$row['time']??'',$row['action']??'',!empty($row['success'])?'true':'false',$row['site']??'',$row['actor']??'',$row['token_id']??'',$row['subject_token_id']??'',$row['remote']??'',wp_json_encode($row['context']??[],JSON_UNESCAPED_SLASHES)]);rewind($stream);$csv=stream_get_contents($stream);fclose($stream);return ['format'=>'csv','count'=>$data['count'],'content'=>$csv];}

    public static function resource_definitions():array {return [
        ['uri'=>'xsofty://site/health','name'=>'site-health','title'=>'Site health','description'=>'Curated WordPress operational health.','mimeType'=>'application/json'],
        ['uri'=>'xsofty://backups/schedule','name'=>'backup-schedule','title'=>'Backup schedule','description'=>'Private backup schedule and retention.','mimeType'=>'application/json'],
        ['uri'=>'xsofty://jobs/recent','name'=>'recent-jobs','title'=>'Recent jobs','description'=>'Recent token-visible asynchronous jobs.','mimeType'=>'application/json'],
        ['uri'=>'xsofty://audit/recent','name'=>'recent-audit','title'=>'Recent audit','description'=>'Recent MCP audit entries.','mimeType'=>'application/json'],
        ['uri'=>'xsofty://approvals/recent','name'=>'recent-approvals','title'=>'Recent approvals','description'=>'Recent token-owned approval requests.','mimeType'=>'application/json'],
    ];}
    public static function resource_scope(string $uri):string {return match($uri){'xsofty://site/health'=>'site_read','xsofty://backups/schedule','xsofty://jobs/recent'=>'backups','xsofty://audit/recent','xsofty://approvals/recent'=>'audit',default=>''};}
    public static function read_resource(string $uri):array {return match($uri){'xsofty://site/health'=>Xsofty_MCP_Operations::health(),'xsofty://backups/schedule'=>Xsofty_MCP_Jobs::schedule_settings(),'xsofty://jobs/recent'=>Xsofty_MCP_Jobs::list_jobs(20),'xsofty://audit/recent'=>self::query_audit(['limit'=>50]),'xsofty://approvals/recent'=>self::list_approvals('all',50),default=>throw new InvalidArgumentException('Unknown resource URI.')};}

    public static function admin_decide():void {if(!current_user_can('manage_options'))wp_die('You do not have permission to decide MCP approvals.');check_admin_referer('xsofty_mcp_approval');try{self::decide((string)($_POST['id']??''),(string)($_POST['decision']??''));$args=['approval_updated'=>'1'];}catch(Throwable $e){$args=['error'=>rawurlencode(substr($e->getMessage(),0,160))];}wp_safe_redirect(add_query_arg(array_merge(['page'=>'xsofty-wordpress-mcp'],$args),admin_url('options-general.php')));exit;}
    public static function render_admin():void {$records=self::list_approvals('all',50,true);echo '<h2>Approval queue</h2>';if(!$records['items']){echo '<p>No approval requests.</p>';return;}echo '<table class="widefat striped" style="max-width:1200px"><thead><tr><th>Created</th><th>Connection</th><th>Tool and exact plan</th><th>Summary</th><th>Status</th><th>Decision</th></tr></thead><tbody>';foreach($records['items'] as $r){$plan=wp_json_encode($r['arguments']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);echo '<tr><td>'.esc_html($r['created_at']).'</td><td><code>'.esc_html($r['token_id']).'</code></td><td><code>'.esc_html($r['tool']).'</code><pre style="white-space:pre-wrap;max-width:420px">'.esc_html($plan).'</pre><small>Plan SHA-256: <code>'.esc_html($r['plan_sha256']??'').'</code></small></td><td>'.esc_html($r['summary']).'</td><td>'.esc_html($r['status']).'</td><td>';if($r['status']==='pending'){foreach(['approved'=>'Approve','rejected'=>'Reject'] as $value=>$label){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="display:inline;margin-right:6px"><input type="hidden" name="action" value="xsofty_mcp_approval"><input type="hidden" name="id" value="'.esc_attr($r['id']).'"><input type="hidden" name="decision" value="'.esc_attr($value).'">';wp_nonce_field('xsofty_mcp_approval');submit_button($label,$value==='approved'?'primary':'secondary','submit',false);echo '</form>';}}echo '</td></tr>';}echo '</tbody></table>';}
}
